[versions]
android-tools-r8 = "8.3.6-dev"
androidx-activity = "1.8.0"
androidx-appcompat = "1.6.1"
androidx-biometric = "1.2.0-alpha05"
androidx-browser = "1.6.0"
androidx-collection = "1.3.0"
androidx-coordinatorlayout = "1.2.0"
androidx-core = "1.12.0"
androidx-fragment = "1.6.1"
androidx-lifecycle = "2.6.2"
androidx-paging = "3.2.1"
androidx-preference = "1.2.1"
androidx-recyclerview = "1.3.1"
androidx-room = "2.6.0-rc01"
androidx-swiperefreshlayout = "1.2.0-alpha01"
coil = "2.4.0"
google-android-material = "1.10.0"
kotlin = "1.9.10"
kotlinx-coroutines = "1.7.3"
okhttp3 = "5.0.0-alpha.11"
okio = "3.6.0"
rikkax-material = { strictly = "1.6.6" }

[libraries]
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-biometric = { module = "androidx.biometric:biometric-ktx", version.ref = "androidx-biometric" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidx-browser" }
androidx-collection = { module = "androidx.collection:collection-ktx", version.ref = "androidx-collection" }
androidx-coordinatorlayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "androidx-coordinatorlayout" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidx-lifecycle" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime-ktx", version.ref = "androidx-paging" }
androidx-preference = { module = "androidx.preference:preference-ktx", version.ref = "androidx-preference" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }

androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "androidx-room" }

androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "androidx-swiperefreshlayout" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
drawer = "com.drakeet.drawer:drawer:1.0.3"
jsoup = "org.jsoup:jsoup:1.16.1"
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
material = { module = "com.google.android.material:material", version.ref = "google-android-material" }

okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttp3" }
okhttp-coroutines = { module = "com.squareup.okhttp3:okhttp-coroutines" }
okio-jvm = { module = "com.squareup.okio:okio-jvm", version.ref = "okio" }

r8 = { module = "com.android.tools:r8", version.ref = "android-tools-r8" }

rikkax-core = "dev.rikka.rikkax.core:core-ktx:1.4.1"
rikkax-insets = "dev.rikka.rikkax.insets:insets:1.3.0"
rikkax-layoutinflater = "dev.rikka.rikkax.layoutinflater:layoutinflater:1.3.0"
rikkax-material = { module = "dev.rikka.rikkax.material:material", version.ref = "rikkax-material" }
rikkax-simplemenu-preference = "dev.rikka.rikkax.preference:simplemenu-preference:1.0.3"

[bundles]
rikkax = ["rikkax-core", "rikkax-insets", "rikkax-layoutinflater", "rikkax-material", "rikkax-simplemenu-preference"]

[plugins]
android-application = { id = "com.android.application", version = "8.1.2" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version = "1.9.10-1.0.13" }
spotless = { id = "com.diffplug.spotless", version = "6.22.0" }
